title = "Carlo Delle Donne"
author = "Carlo Delle Donne"
description = """
Embedded systems engineer
PhD in quantum communication systems
"""
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = ["css/custom.css", "css/font.css"]
customJs = []
mainSections = []
images = ["images/site-feature-image.png"]

# Footer info
copyright = "2020–{{ YEAR }} Carlo Delle Donne"
sourceUrl = "https://github.com/cdelledonne/cdelledonne.eu"

[license]
name = "CC BY-NC 4.0"
url = "https://creativecommons.org/licenses/by-nc/4.0/"

# Social links.
# Use 'fab' for brand icons, use 'fas' for standard solid icons.

[[socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/cdelledonne/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/cdelledonne"

[[socialIcons]]
icon = "fas fa-graduation-cap"
title = "Google Scholar"
url = "https://scholar.google.com/citations?user=bBtN-F8AAAAJ"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:cdelledonne@mailbox.org"
