baseURL = "https://cdelledonne.eu/"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT=true

# Enable Disqus
# disqusShortname = ""

# Google Analytics
# googleAnalytics = "UA-123-45"

[params]
title = "Carlo Delle Donne"
created = 2020
author = "Carlo Delle Donne"
description = "PhD student at TU Delft"
sourceUrl = "https://github.com/cdelledonne/cdelledonne.eu"
license = "CC BY-NC 4.0"
licenseUrl = "https://creativecommons.org/licenses/by-nc/4.0/"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = ["css/custom.css", "css/font.css"]
customJs = []
mainSections = []
images = ["images/site-feature-image.png"]
# Google Site Verification
# googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

# Math settings.

[params.math]
# Enable math support globally (default: false). Can always be enabled per page.
enable = false
# Options: "katex" (default), "mathjax".
use = "katex"

# Social links.
# Use 'fab' for brand icons, use 'fas' for standard solid icons.

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/cdelledonne/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/cdelledonne"

[[params.socialIcons]]
icon = "fas fa-graduation-cap"
title = "Google Scholar"
url = "https://scholar.google.com/citations?user=bBtN-F8AAAAJ"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:carlo.delle.donne@gmail.com"

# Menu items.

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Research"
  weight = 200
  identifier = "research"
  url = "/research/"

  [[menu.main]]
  name = "Projects"
  weight = 300
  identifier = "projects"
  url = "/projects/"

  # [[menu.main]]
  # name = "Posts"
  # weight = 400
  # identifier = "posts"
  # url = "/posts/"
